version: "3"
services:
  api:
    container_name: api
    image: node_redis:0.0.1
    restart: always
    build: .
    ports:
      - "2020:2020"
    environment:
      DB_URL: "mongodb://mongo:27017"
      DATABASE_NAME: "myproject"
      REDIS_URL: "redis://redis:6379"
      REDIS_KEY: "TESTE"
      REDIS_TIME: 60
    links:
      - mongo
      - redis
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
