version: "3"
services:
  api:
    container_name: api
    image: node_dynamo:0.0.1
    restart: always
    build: .
    ports:
      - "2020:2020"
    environment:
      DB_URL: "http://dynamodb:8000"
      DATABASE_NAME: "MOVIES"
      REDIS_URL: "redis://redis:6379"
      REDIS_KEY: "TESTE"
      REDIS_TIME: 60
      AWS_ACCESS_KEY_ID: "AKIAJQ4DUWC33K3XUIXQ"
      AWS_SECRET_ACCESS_KEY: "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"
    links:
      - dynamodb
      - redis
  dynamodb:
    container_name: dynamodb
    image: amazon/dynamodb-local
    volumes:
      - $PWD/dynamodb-data:/var/lib/dynamodblocal
    ports:
      - "8000:8000"
  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
